name: App tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        #pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # TODO(roberi) Try with conda env create -f environment.yml
    - name: Analyzing the code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # TODO(roberi): Check https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        aws-access-key-id: ASIATZFWYYDCY3QVE55U
        aws-secret-access-key: vYHKwlJeLNtFpZmvSraYc34yvWOG72GaMElZbFpP
        aws-session-token: FwoGZXIvYXdzEKf//////////wEaDP7uTfMbX+B+ky+hEyK7Aebg86YDKiNdwTZS85cGr9AkR1ohacrl+NI27545W470rFpKOLNpyNZ8br8UqJvlq/1eB+P+HKrQjhFuFfUXEyIxUH261KMsp4t2qzc87MowgAlYMe1J/cdYWmUwEEL1+k2yXuitfFIlhwwYznY7gO6XHRz7eo6STNjCPkj58UQoDxdmyqrrZzhtcE9YRe8wjixyR4ml8UM1c79kXwY1PUmm9IkSTlyBpwBCQnK/rmcPykD3UBvEl5MHAdUo/6OSjwYyLUowtoKXsNiyCHQ/VjwfRScZcOBQNAuUNEFEvyTxa17sGwuVZfcw6SI7J/wYkw==
        aws-region: eu-north-1
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    - name: Pull data from DVC
      run: |
        dvc remote add -df s3-bucket s3://euriskoudacityproject3
        dvc pull
    - name: Run unit tests
      run: |
        pytest
      