name: App tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        #pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # TODO(roberi) Try with conda env create -f environment.yml
    - name: Analyzing the code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # TODO(roberi): Check https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        aws-access-key-id: ASIATZFWYYDCRL7LHDVA
        aws-secret-access-key: M8g0fS113UeI3jsBxKbhyiGeY3uL1KitS1S5XM
        aws-session-token: FwoGZXIvYXdzEKX//////////wEaDMFwdhSse1VTPSE9kCK7Ab4CgQ0THxHYs/eelQRzh8w9PL7TRHax4bYbIxkYeyaFZLlw6lN6eLry0aHF9/d//BCC0bCIijQHTCBWQWJDgtwW1hp3fEAmKwdZVYem6RTunVtoBOkUlP1RUl3yOc7tdb0s2HbaIgsjDqQ1B0EIt8OxJpRFnD/AppRQDqhj0HRFQEJ7TyO0XsFvtFjRizbb64Ggn8xgJo6/FV2Q46jGfcvyw1iYlTXJ2hJOZuOfJNaPH6M4hit3c2C9w48oseSRjwYyLXnn8tPYmdVA+D8IWgGyjsMBfOagJgveWoDrG8Szz3kAZLVskaSKhL8UJsnc9w==
        aws-region: eu-north-1
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    - name: Pull data from DVC
      run: |
        dvc remote add -df s3-bucket s3://euriskoudacityproject3
        dvc pull
    - name: Run unit tests
      run: |
        pytest
      